#! /bin/bash -e

ROOT=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
IOJS_VER=v1.5.1
NPM_HASH_FILE=$ROOT/node_modules/.exhibition.md5

##### Configuration helpers

get_iojs_os() {
  uname -s | tr '[:upper:]' '[:lower:]'
}

get_iojs_arch() {
  if [ "$(uname -m)" == "x86_64" ];
  then
    echo 'x64';
  else
    echo 'x86';
  fi
}

# Hack to generate md5 in cross platform way (using node which we install)
md5() {
  local path=$1
  # WTF? This super long js string will read a file and output a md5... This
  # looks terrible but saves the need of dealing with md5/md5sum utils which
  # vary in output..
  local cmd="var crypto = require('crypto');var fs = require('fs');console.log(crypto.createHash('md5').update(fs.readFileSync('$path', 'utf8')).digest('hex'));"
  node -e "$cmd"
}


# Download IOJS and return the path to the bin directory...
download_iojs() {
  local version=$1
  local url="https://iojs.org/dist/$IOJS_VER/iojs-${IOJS_VER}-$(get_iojs_os)-$(get_iojs_arch).tar.gz"
  local path="$ROOT/.iojs/$version/"

  # Already installed iojs...
  if [ -x $path/bin/iojs ];
  then
    echo $path/bin/
    return
  fi

  # Install IO JS...
  mkdir -p $path
  cd $path
  curl $url | tar -xz --strip-components 1
  cd -

  # Validate the install...
  if ! $path/bin/iojs --version ;
  then
    echo "Error installing IO JS"
    exit 1
  fi

  echo $path/bin/
}

npm_install() {
  local package_hash=$(md5 $ROOT/package.json)
  local install_hash=""

  # Wrapped in this if statement to suppress any unwanted output...
  if [ -f $NPM_HASH_FILE ];
  then
    install_hash=$(cat $NPM_HASH_FILE)
  fi

  if [ "$install_hash" == "$package_hash" ];
  then
    return
  fi

  cd $ROOT
  npm install
  cd -
  echo $package_hash > $NPM_HASH_FILE
}

##### Configuration for exhibition
IOJS_BIN=$(download_iojs $IOJS_VER)
PATH=$IOJS_BIN:$PATH
npm_install

##### Your Command stuff with the clean node environment...
exec node build/index.js examples $@
